import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
import { cn } from "../_shared/variants";
export const Table = React.forwardRef(({ className, ...props }, ref) => (_jsx("div", { className: "relative w-full overflow-x-auto", children: _jsx("table", { ref: ref, className: cn("w-full caption-bottom border-collapse text-sm", className), ...props }) })));
Table.displayName = "Table";
export const TableHeader = React.forwardRef(({ className, ...props }, ref) => (_jsx("thead", { ref: ref, className: cn("[&_tr]:border-b [&_tr]:border-[color:var(--sx-color-border)]", className), ...props })));
TableHeader.displayName = "TableHeader";
export const TableBody = React.forwardRef(({ className, ...props }, ref) => (_jsx("tbody", { ref: ref, className: cn("[&_tr:last-child]:border-0", className), ...props })));
TableBody.displayName = "TableBody";
export const TableFooter = React.forwardRef(({ className, ...props }, ref) => (_jsx("tfoot", { ref: ref, className: cn("border-t border-[color:var(--sx-color-border)] bg-[color:var(--sx-color-surface-muted)] font-medium [&>tr]:last:border-b-0", className), ...props })));
TableFooter.displayName = "TableFooter";
export const TableRow = React.forwardRef(({ className, ...props }, ref) => (_jsx("tr", { ref: ref, className: cn("border-b border-[color:var(--sx-color-border)] transition-colors hover:bg-[color:var(--sx-color-surface-muted)] data-[state=selected]:bg-[color:var(--sx-color-primary-muted)]", className), ...props })));
TableRow.displayName = "TableRow";
export const TableHead = React.forwardRef(({ className, ...props }, ref) => (_jsx("th", { ref: ref, className: cn("h-11 px-4 text-left align-middle text-xs font-semibold uppercase tracking-[0.08em] text-[color:var(--sx-color-foreground-muted)]", className), ...props })));
TableHead.displayName = "TableHead";
export const TableCell = React.forwardRef(({ className, ...props }, ref) => (_jsx("td", { ref: ref, className: cn("px-4 py-3 align-middle text-[color:var(--sx-color-foreground)]", className), ...props })));
TableCell.displayName = "TableCell";
export const TableCaption = React.forwardRef(({ className, ...props }, ref) => (_jsx("caption", { ref: ref, className: cn("mt-4 text-sm text-[color:var(--sx-color-foreground-muted)]", className), ...props })));
TableCaption.displayName = "TableCaption";
