import { type LucideIcon } from "lucide-react";
import type { IconName, IconProps } from "./shared";
export declare const iconMap: Record<IconName, LucideIcon>;
export declare function Icon({ className, color, name, size, strokeWidth }: IconProps): import("react/jsx-runtime").JSX.Element;
export declare function AddIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function CloseIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function CheckIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function CalendarIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function SearchIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function GridIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function SettingsIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function UndoIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function RedoIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function PanelLeftIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function PanelRightIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function PanelTopIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function PanelBottomIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function ChevronLeftIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function ChevronRightIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function ChevronDownIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function LayoutTemplateIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function PackageIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function PaletteIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function TerminalIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function MoonIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function SunIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function ColumnsIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function RowsIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function LayoutIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function ActivityIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function BookOpenIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function FolderIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
export declare function FileIcon(props: Omit<IconProps, "name">): import("react/jsx-runtime").JSX.Element;
//# sourceMappingURL=index.web.d.ts.map