import type { CSSProperties } from "react";
import { Calendar, Checkbox, Combobox, ComboboxContent, ComboboxEmpty, ComboboxInput, ComboboxItem, ComboboxList, ComboboxTrigger, ComboboxValue, DatePicker, InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot, Input, Label, NativeSelect, Popover, PopoverContent, PopoverTrigger, RadioGroup, RadioGroupItem, Select, SelectContent, SelectItem, SelectTrigger, SelectValue, Slider, Switch } from "synthex-ui/components";
import type { BuilderNode } from "../types";
import { toStringList } from "../utils";

export function renderForms(n: BuilderNode, f: CSSProperties, showEditExpanded: boolean) {
  const options = toStringList(n.props.options);
  switch (n.type) {
    case "Input": return <div style={{ ...f, display: "flex", flexDirection: "column", gap: 4, justifyContent: "center" }}>{n.props.label && <Label>{n.props.label}</Label>}<Input placeholder={n.props.placeholder} readOnly /></div>;
    case "Checkbox": return <div style={{ ...f, display: "flex", alignItems: "center", gap: 8 }}><Checkbox /><Label>{n.props.label}</Label></div>;
    case "Switch": return <div style={{ ...f, display: "flex", alignItems: "center", gap: 8 }}><Switch /><Label>{n.props.label}</Label></div>;
    case "RadioGroup": return <div style={{ ...f, display: "flex", alignItems: "center" }}><RadioGroup defaultValue={n.props.value || options[0]}>{(options.length ? options : ["Option 1", "Option 2"]).map((option) => <RadioGroupItem key={option} value={option}>{option}</RadioGroupItem>)}</RadioGroup></div>;
    case "Slider": return <div style={{ ...f, display: "flex", alignItems: "center" }}><Slider defaultValue={[n.props.value || 50]} /></div>;
    case "Select": return <div style={{ ...f, display: "flex", alignItems: "flex-start", padding: 10 }}><Select defaultValue={n.props.value} open={showEditExpanded ? true : undefined} placeholder={n.props.placeholder}><SelectTrigger aria-label={`${n.id}-select`}><SelectValue /></SelectTrigger><SelectContent>{(options.length ? options : ["Option 1", "Option 2"]).map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></div>;
    case "Combobox": return <div style={{ ...f, display: "flex", alignItems: "flex-start", padding: 10 }}><Combobox defaultValue={n.props.value} open={showEditExpanded ? true : undefined} placeholder={n.props.placeholder}><ComboboxTrigger aria-label={`${n.id}-combobox`}><ComboboxValue /></ComboboxTrigger><ComboboxContent><ComboboxInput aria-label={`${n.id}-combobox-search`} /><ComboboxList><ComboboxEmpty>No results.</ComboboxEmpty>{(options.length ? options : ["Option 1", "Option 2"]).map((option) => <ComboboxItem key={option} value={option}>{option}</ComboboxItem>)}</ComboboxList></ComboboxContent></Combobox></div>;
    case "DatePicker": return showEditExpanded ? <div style={{ ...f, display: "flex", alignItems: "flex-start", padding: 10 }}><Popover open><PopoverTrigger className="inline-flex h-10 w-full items-center justify-between gap-3 rounded-[var(--sx-radius-md)] border border-[color:var(--sx-color-border)] bg-[color:var(--sx-color-surface-raised)] px-3.5 text-sm text-[color:var(--sx-color-foreground)]"><span>{n.props.placeholder || "Pick a date"}</span><span aria-hidden="true">📅</span></PopoverTrigger><PopoverContent className="min-w-[19rem] p-0"><Calendar className="border-0 shadow-none" /></PopoverContent></Popover></div> : <div style={{ ...f, display: "flex", alignItems: "flex-start", padding: 10 }}><DatePicker placeholder={n.props.placeholder || "Pick a date"} /></div>;
    case "InputOTP": return <div style={{ ...f, display: "flex", alignItems: "center", justifyContent: "center" }}><InputOTP defaultValue={n.props.value || ""} length={Number(n.props.length) || 4}><InputOTPGroup><InputOTPSlot index={0} aria-label="OTP digit 1" /><InputOTPSlot index={1} aria-label="OTP digit 2" /><InputOTPSeparator /><InputOTPSlot index={2} aria-label="OTP digit 3" /><InputOTPSlot index={3} aria-label="OTP digit 4" /></InputOTPGroup></InputOTP></div>;
    case "NativeSelect": return <div style={{ ...f, display: "flex", alignItems: "center" }}><NativeSelect defaultValue={n.props.value || options[0]}>{(options.length ? options : ["Option 1", "Option 2"]).map((option) => <option key={option} value={option}>{option}</option>)}</NativeSelect></div>;
    default: return null;
  }
}
