import type { CSSProperties } from "react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger, Breadcrumb, Button, Collapsible, CollapsibleContent, CollapsibleTrigger, Menubar, MenubarContent, MenubarItem, MenubarLabel, MenubarMenu, MenubarSeparator, MenubarTrigger, NavigationMenu, NavigationMenuContent, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, Pagination, PaginationContent, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious, ResizableHandle, ResizablePanel, ResizablePanelGroup, Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, Tabs, TabsContent, TabsList, TabsTrigger } from "synthex-ui/components";
import type { BuilderNode } from "../types";
import { toStringList } from "../utils";

export function renderNavigation(n: BuilderNode, f: CSSProperties, showEditExpanded: boolean) {
  const items = toStringList(n.props.items);
  switch (n.type) {
    case "Tabs": return <div style={f}><Tabs defaultValue={(n.props.tabs || [])[0]?.id}><TabsList>{(n.props.tabs || []).map((t: any) => <TabsTrigger key={t.id} value={t.id}>{t.label}</TabsTrigger>)}</TabsList>{(n.props.tabs || []).map((t: any) => <TabsContent key={t.id} value={t.id} style={{ fontSize: 13, padding: 8 }}>{t.content}</TabsContent>)}</Tabs></div>;
    case "Accordion": return <div style={f}><Accordion type="single" collapsible>{(n.props.items || []).map((i: any) => <AccordionItem key={i.id} value={i.id}><AccordionTrigger>{i.title}</AccordionTrigger><AccordionContent>{i.content}</AccordionContent></AccordionItem>)}</Accordion></div>;
    case "Breadcrumb": return <div style={{ ...f, display: "flex", alignItems: "center", gap: 6, fontSize: 13 }}><Breadcrumb>{toStringList(n.props.items, ["Home", "Current"]).join(" / ")}</Breadcrumb></div>;
    case "Pagination": return <div style={f}><Pagination><PaginationContent><PaginationItem><PaginationPrevious /></PaginationItem>{toStringList(n.props.pages, ["1", "2", "3"]).map((page) => <PaginationItem key={page}><PaginationLink isActive={page === String(n.props.activePage || "1")}>{page}</PaginationLink></PaginationItem>)}<PaginationItem><PaginationNext /></PaginationItem></PaginationContent></Pagination></div>;
    case "NavigationMenu": return <div style={{ ...f, padding: 10 }}><NavigationMenu defaultValue="item-0" value={showEditExpanded ? "item-0" : undefined}><NavigationMenuList>{(items.length ? items : ["Guides", "API"]).slice(0, 2).map((item, index) => <NavigationMenuItem key={item} value={`item-${index}`}><NavigationMenuTrigger>{item}</NavigationMenuTrigger></NavigationMenuItem>)}<NavigationMenuLink href="#">{items[2] || "Changelog"}</NavigationMenuLink></NavigationMenuList>{(items.length ? items : ["Guides", "API"]).slice(0, 2).map((item, index) => <NavigationMenuItem key={`${item}-content`} value={`item-${index}`}><NavigationMenuContent>{item} content</NavigationMenuContent></NavigationMenuItem>)}</NavigationMenu></div>;
    case "Menubar": return <div style={{ ...f, padding: 10 }}><Menubar>{(items.length ? items : ["File", "Edit", "View"]).map((item, index) => <MenubarMenu key={item} open={showEditExpanded && index === 0 ? true : undefined}><MenubarTrigger>{item}</MenubarTrigger><MenubarContent><MenubarLabel>{item}</MenubarLabel><MenubarItem>{item} action</MenubarItem><MenubarSeparator /><MenubarItem>More {item.toLowerCase()}</MenubarItem></MenubarContent></MenubarMenu>)}</Menubar></div>;
    case "Sidebar": return <div style={f}><SidebarProvider defaultOpen><div style={{ display: "flex", minHeight: "100%", border: "1px solid var(--sx-color-border)", borderRadius: "var(--sx-radius-lg)", overflow: "hidden" }}><Sidebar><SidebarHeader><SidebarTrigger /></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Navigation</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{(items.length ? items : ["Dashboard", "Settings"]).map((item, index) => <SidebarMenuItem key={item}><SidebarMenuButton active={index === 0}>{item}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter /></Sidebar><SidebarInset><div style={{ padding: 12, fontSize: 13 }}>Sidebar content</div></SidebarInset></div></SidebarProvider></div>;
    case "Resizable": return <ResizablePanelGroup direction="horizontal" style={f}><ResizablePanel defaultSize={58}><div style={{ display: "flex", height: "100%", alignItems: "center", justifyContent: "center", fontSize: 13 }}>{toStringList(n.props.panes, ["Canvas", "Inspector"])[0]}</div></ResizablePanel><ResizableHandle /><ResizablePanel defaultSize={42}><div style={{ display: "flex", height: "100%", alignItems: "center", justifyContent: "center", fontSize: 13 }}>{toStringList(n.props.panes, ["Canvas", "Inspector"])[1] || "Inspector"}</div></ResizablePanel></ResizablePanelGroup>;
    case "Collapsible": return <div style={f}><Collapsible open={showEditExpanded ? true : undefined}><CollapsibleTrigger style={{ padding: 8, fontSize: 13, border: "1px solid var(--sx-color-border)", borderRadius: "var(--sx-radius-md)", width: "100%", background: "var(--sx-color-surface)", textAlign: "left" }}>▾ {n.props.trigger || "Toggle Collapsible"}</CollapsibleTrigger><CollapsibleContent><div style={{ padding: 12, fontSize: 13, border: "1px solid var(--sx-color-border)", borderRadius: "var(--sx-radius-md)", marginTop: 6 }}>{n.props.content}</div></CollapsibleContent></Collapsible></div>;
    default: return null;
  }
}
