import type { CSSProperties } from "react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger, Button, ContextMenu, ContextMenuContent, ContextMenuItem, ContextMenuLabel, ContextMenuSeparator, ContextMenuTrigger, Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger, Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerTitle, DrawerTrigger, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger, HoverCard, HoverCardContent, HoverCardTrigger, Popover, PopoverContent, PopoverTrigger, Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, Tooltip, TooltipContent, TooltipTrigger, useToast } from "synthex-ui/components";
import type { BuilderNode } from "../types";
import { toStringList } from "../utils";

function ToastNode({ title, description }: { title?: string; description?: string }) {
  const { toast } = useToast();
  return <div style={{ width: "100%", height: "100%", display: "flex", alignItems: "center", justifyContent: "center" }}><Button variant="outline" onClick={() => toast({ title: title || "Toast!", description: description || "This is a toast notification." })}>Show Toast</Button></div>;
}

export function renderOverlays(n: BuilderNode, f: CSSProperties, showEditExpanded: boolean) {
  const items = toStringList(n.props.items);
  switch (n.type) {
    case "Dialog": return <div style={{ ...f, display: "flex", alignItems: "center", justifyContent: "center" }}><Dialog><DialogTrigger asChild><Button variant="outline">{n.props.trigger}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{n.props.title}</DialogTitle><DialogDescription>{n.props.description}</DialogDescription></DialogHeader><DialogFooter><DialogClose asChild><Button variant="destructive">Cancel</Button></DialogClose><DialogClose asChild><Button variant="outline">Confirm</Button></DialogClose></DialogFooter></DialogContent></Dialog></div>;
    case "AlertDialog": return <div style={{ ...f, display: "flex", alignItems: "center", justifyContent: "center" }}><AlertDialog><AlertDialogTrigger asChild><Button variant="destructive">{n.props.trigger}</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{n.props.title}</AlertDialogTitle><AlertDialogDescription>{n.props.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>;
    case "Sheet": return <div style={{ ...f, display: "flex", alignItems: "center", justifyContent: "center" }}><Sheet><Button variant="outline">{n.props.trigger}</Button><SheetContent><SheetHeader><SheetTitle>{n.props.title}</SheetTitle><SheetDescription>{n.props.description}</SheetDescription></SheetHeader><div style={{ padding: "16px 0", fontSize: 13 }}>{n.props.content}</div></SheetContent></Sheet></div>;
    case "Popover": return <div style={{ ...f, display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: 12 }}><Popover open={showEditExpanded ? true : undefined}><PopoverTrigger asChild><Button variant="outline">{n.props.trigger}</Button></PopoverTrigger><PopoverContent><div style={{ fontSize: 13 }}>{n.props.content}</div></PopoverContent></Popover></div>;
    case "Tooltip": return <div style={{ ...f, display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: 12 }}><Tooltip open={showEditExpanded ? true : undefined}><TooltipTrigger asChild><Button variant="outline">{n.props.trigger}</Button></TooltipTrigger><TooltipContent>{n.props.content}</TooltipContent></Tooltip></div>;
    case "DropdownMenu": return <div style={{ ...f, display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: 12 }}><DropdownMenu open={showEditExpanded ? true : undefined}><DropdownMenuTrigger asChild><Button variant="outline">{n.props.trigger}</Button></DropdownMenuTrigger><DropdownMenuContent>{items.map((m, i) => m === "-" ? <DropdownMenuSeparator key={i} /> : <DropdownMenuItem key={i}>{m}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div>;
    case "ContextMenu": return <div style={{ ...f, display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: 12 }}><ContextMenu><ContextMenuTrigger style={{ width: 180, height: 40, border: "1px dashed var(--sx-color-border)", borderRadius: "var(--sx-radius-md)", display: "flex", alignItems: "center", justifyContent: "center", color: "var(--sx-color-foreground-muted)", fontSize: 13 }}>{n.props.trigger}</ContextMenuTrigger><ContextMenuContent><ContextMenuLabel>Actions</ContextMenuLabel>{items.map((m, i) => m === "-" ? <ContextMenuSeparator key={i} /> : <ContextMenuItem key={i}>{m}</ContextMenuItem>)}</ContextMenuContent></ContextMenu></div>;
    case "HoverCard": return <div style={{ ...f, display: "flex", alignItems: "flex-start", justifyContent: "center", paddingTop: 12 }}><HoverCard open={showEditExpanded ? true : undefined}><HoverCardTrigger asChild><Button variant="link">{n.props.trigger}</Button></HoverCardTrigger><HoverCardContent><div style={{ fontSize: 13 }}><div style={{ fontWeight: 600 }}>{n.props.title}</div><div style={{ color: "var(--sx-color-foreground-muted)", marginTop: 4 }}>{n.props.description}</div></div></HoverCardContent></HoverCard></div>;
    case "Toast": return <ToastNode title={n.props.title} description={n.props.description} />;
    case "Drawer": return <div style={{ ...f, display: "flex", alignItems: "center", justifyContent: "center" }}><Drawer><DrawerTrigger className="inline-flex h-10 items-center justify-center rounded-[var(--sx-radius-md)] border border-[color:var(--sx-color-border)] bg-[color:var(--sx-color-surface)] px-4 text-sm font-medium">{n.props.trigger}</DrawerTrigger><DrawerContent><DrawerHeader><DrawerTitle>{n.props.title}</DrawerTitle><DrawerDescription>{n.props.description}</DrawerDescription></DrawerHeader><DrawerFooter><DrawerClose className="inline-flex h-10 items-center justify-center rounded-[var(--sx-radius-md)] border border-[color:var(--sx-color-border)] bg-[color:var(--sx-color-surface)] px-4 text-sm font-medium">Close</DrawerClose></DrawerFooter></DrawerContent></Drawer></div>;
    default: return null;
  }
}
