import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from "react";
import { Button, Input, Table, TableBody, TableCell, TableRow, } from "../components/index.native";
import { SearchIcon } from "../icons/index.native";
import { Inline, Stack, Surface, Text } from "../primitives/index.native";
import { H2 } from "../typography/typography.native";
export function DashboardView({ metrics, updates, chartData, searchValue, onSearchChange, onDocumentationClick, onRepositoryClick, }) {
    return (_jsxs(Stack, { grow: true, gap: "xl", padding: "xl", background: "background", children: [_jsx(Surface, { tone: "raised", border: true, padding: "md", radius: "xl", children: _jsx(Inline, { align: "center", justify: "space-between", gap: "md", children: _jsxs(Inline, { align: "center", gap: "lg", grow: true, children: [_jsx(Text, { size: "lg", weight: "bold", children: "Synthex" }), _jsx(Surface, { tone: "muted", radius: "pill", paddingX: "md", paddingY: "xs", grow: true, children: _jsxs(Inline, { align: "center", gap: "sm", children: [_jsx(SearchIcon, { size: 16, color: "#71717a" }), _jsx(Input, { placeholder: "Search...", style: { height: 32, padding: 0, flex: 1 }, value: searchValue, onChangeText: onSearchChange })] }) })] }) }) }), _jsx(Stack, { gap: "md", children: _jsx(H2, { children: "Dashboard" }) }), _jsx(Stack, { gap: "md", children: metrics.map((metric, i) => (_jsx(Surface, { tone: "raised", padding: "lg", radius: "lg", style: { position: "relative", overflow: "hidden" }, children: _jsxs(Stack, { gap: "sm", children: [_jsxs(Inline, { justify: "space-between", align: "center", children: [_jsx(Text, { size: "sm", tone: "muted", children: metric.label }), _jsx(Text, { size: "lg", children: metric.icon })] }), _jsxs(Stack, { gap: "xs", children: [_jsx(Text, { size: "2xl", weight: "bold", children: metric.value }), metric.description ? (_jsxs(Inline, { gap: "xs", align: "center", children: [metric.trend ? (_jsx(Text, { size: "xs", weight: "medium", style: { color: "#10b981" }, children: metric.trend.value })) : null, _jsx(Text, { size: "xs", tone: "muted", children: metric.description })] })) : null] })] }) }, i))) }), _jsx(Surface, { tone: "raised", padding: "lg", radius: "lg", children: _jsxs(Stack, { gap: "lg", children: [_jsxs(Stack, { gap: "xs", children: [_jsx(Text, { weight: "semibold", size: "lg", children: "Usage Overview" }), _jsx(Text, { size: "sm", tone: "muted", children: "Monthly NPM downloads" })] }), _jsx(Inline, { align: "flex-end", justify: "space-between", gap: "xs", style: { height: 120 }, children: chartData.map((data) => (_jsxs(Stack, { grow: true, gap: "xs", align: "center", children: [_jsx(Surface, { tone: "accent", radius: "sm", width: "100%", style: {
                                            height: `${data.value}%`,
                                            opacity: 0.2,
                                            minHeight: 2,
                                        } }), _jsx(Text, { style: { fontSize: 8 }, tone: "muted", children: data.month })] }, data.month))) })] }) }), _jsx(Surface, { tone: "raised", padding: 0, radius: "lg", grow: true, children: _jsxs(Stack, { children: [_jsx(Surface, { tone: "transparent", padding: "lg", children: _jsxs(Inline, { justify: "space-between", align: "center", children: [_jsx(Text, { weight: "semibold", size: "lg", children: "Recent Updates" }), _jsx(Button, { variant: "outline", size: "sm", onPress: onRepositoryClick, children: _jsx(Text, { size: "xs", children: "Repo" }) })] }) }), _jsx(Table, { children: _jsx(TableBody, { children: updates.map((update, i) => (_jsxs(TableRow, { children: [_jsx(TableCell, { style: { width: 60, paddingLeft: 16 }, children: _jsx(Surface, { tone: "muted", radius: "pill", width: 36, height: 36, align: "center", justify: "center", children: _jsx(Text, { size: "xs", weight: "bold", children: update.initials }) }) }), _jsx(TableCell, { children: _jsxs(Stack, { gap: "xs", children: [_jsx(Text, { size: "sm", weight: "semibold", children: update.title }), _jsxs(Text, { size: "xs", tone: "muted", children: ["@", update.user, " \u2022 ", update.time] })] }) })] }, i))) }) })] }) })] }));
}
