import type { ComponentDef } from "./types";

export const CATEGORIES = ["Layout", "Typography", "Actions", "Form", "Data Display", "Navigation", "Overlay", "Feedback"];
export const GRID = 20;

export const COMPONENTS: ComponentDef[] = [
  { type: "Container", label: "Container", icon: "⬜", category: "Layout" },
  { type: "Spacer", label: "Spacer", icon: "↕", category: "Layout" },
  { type: "Separator", label: "Separator", icon: "—", category: "Layout" },
  { type: "AspectRatio", label: "Aspect Ratio", icon: "⊡", category: "Layout" },
  { type: "ScrollArea", label: "Scroll Area", icon: "↕", category: "Layout" },
  { type: "Resizable", label: "Resizable", icon: "⇲", category: "Layout" },
  { type: "Heading", label: "Heading", icon: "H", category: "Typography" },
  { type: "Text", label: "Paragraph", icon: "T", category: "Typography" },
  { type: "Lead", label: "Lead Text", icon: "L", category: "Typography" },
  { type: "Muted", label: "Muted Text", icon: "M", category: "Typography" },
  { type: "Small", label: "Small Text", icon: "s", category: "Typography" },
  { type: "Kbd", label: "Keyboard", icon: "⌘", category: "Typography" },
  { type: "Button", label: "Button", icon: "▶", category: "Actions" },
  { type: "ButtonGroup", label: "Button Group", icon: "▶▶", category: "Actions" },
  { type: "Toggle", label: "Toggle", icon: "⇄", category: "Actions" },
  { type: "ToggleGroup", label: "Toggle Group", icon: "⇄⇄", category: "Actions" },
  { type: "Input", label: "Input", icon: "✎", category: "Form" },
  { type: "Textarea", label: "Textarea", icon: "☰", category: "Form" },
  { type: "Checkbox", label: "Checkbox", icon: "☑", category: "Form" },
  { type: "Switch", label: "Switch", icon: "◐", category: "Form" },
  { type: "RadioGroup", label: "Radio Group", icon: "◉", category: "Form" },
  { type: "Select", label: "Select", icon: "▾", category: "Form" },
  { type: "Combobox", label: "Combobox", icon: "⊞", category: "Form" },
  { type: "DatePicker", label: "Date Picker", icon: "📅", category: "Form" },
  { type: "Slider", label: "Slider", icon: "⊶", category: "Form" },
  { type: "InputOTP", label: "OTP Input", icon: "●●●", category: "Form" },
  { type: "NativeSelect", label: "Native Select", icon: "▾", category: "Form" },
  { type: "Label", label: "Label", icon: "🏷", category: "Form" },
  { type: "Form", label: "Form", icon: "📋", category: "Form" },
  { type: "Card", label: "Card", icon: "▢", category: "Data Display" },
  { type: "Badge", label: "Badge", icon: "●", category: "Data Display" },
  { type: "Avatar", label: "Avatar", icon: "👤", category: "Data Display" },
  { type: "Image", label: "Image", icon: "▣", category: "Data Display" },
  { type: "Table", label: "Table", icon: "▦", category: "Data Display" },
  { type: "DataTable", label: "Data Table", icon: "▤", category: "Data Display" },
  { type: "Calendar", label: "Calendar", icon: "📅", category: "Data Display" },
  { type: "Progress", label: "Progress", icon: "◔", category: "Data Display" },
  { type: "Skeleton", label: "Skeleton", icon: "▒", category: "Data Display" },
  { type: "Spinner", label: "Spinner", icon: "◌", category: "Data Display" },
  { type: "Empty", label: "Empty State", icon: "∅", category: "Data Display" },
  { type: "Carousel", label: "Carousel", icon: "◁▷", category: "Data Display" },
  { type: "Tabs", label: "Tabs", icon: "⊞", category: "Navigation" },
  { type: "Accordion", label: "Accordion", icon: "≡", category: "Navigation" },
  { type: "Breadcrumb", label: "Breadcrumb", icon: "›", category: "Navigation" },
  { type: "Pagination", label: "Pagination", icon: "«»", category: "Navigation" },
  { type: "NavigationMenu", label: "Nav Menu", icon: "☰", category: "Navigation" },
  { type: "Menubar", label: "Menubar", icon: "≡", category: "Navigation" },
  { type: "Sidebar", label: "Sidebar", icon: "⊏", category: "Navigation" },
  { type: "Dialog", label: "Dialog", icon: "□", category: "Overlay" },
  { type: "AlertDialog", label: "Alert Dialog", icon: "⚠", category: "Overlay" },
  { type: "Sheet", label: "Sheet", icon: "⊐", category: "Overlay" },
  { type: "Drawer", label: "Drawer", icon: "⊏", category: "Overlay" },
  { type: "Popover", label: "Popover", icon: "💬", category: "Overlay" },
  { type: "HoverCard", label: "Hover Card", icon: "🃏", category: "Overlay" },
  { type: "Tooltip", label: "Tooltip", icon: "💡", category: "Overlay" },
  { type: "DropdownMenu", label: "Dropdown", icon: "▾", category: "Overlay" },
  { type: "ContextMenu", label: "Context Menu", icon: "⊞", category: "Overlay" },
  { type: "Command", label: "Command", icon: "⌘", category: "Overlay" },
  { type: "Toast", label: "Toast", icon: "🔔", category: "Overlay" },
  { type: "Alert", label: "Alert", icon: "ℹ", category: "Feedback" },
  { type: "Collapsible", label: "Collapsible", icon: "⊟", category: "Feedback" },
];
