export function defaults(type: string): { props: Record<string, any>; w: number; h: number } {
  const map: Record<string, { props: Record<string, any>; w: number; h: number }> = {
    Container: { props: { border: true }, w: 400, h: 200 }, Spacer: { props: {}, w: 200, h: 40 }, Separator: { props: {}, w: 300, h: 4 }, AspectRatio: { props: { ratio: "16/9" }, w: 320, h: 180 }, ScrollArea: { props: { items: ["Release notes", "Design tokens", "Runtime adapters", "Theming hooks", "Preview surfaces", "CLI integration", "Migration guide"] }, w: 320, h: 220 }, Resizable: { props: { panes: ["Canvas", "Inspector"] }, w: 420, h: 220 },
    Heading: { props: { text: "Heading", level: "h2" }, w: 300, h: 60 }, Text: { props: { text: "Paragraph text goes here." }, w: 360, h: 80 }, Lead: { props: { text: "Lead text — prominent intro paragraph." }, w: 400, h: 60 }, Muted: { props: { text: "Muted helper text." }, w: 260, h: 40 }, Small: { props: { text: "Small caption text." }, w: 200, h: 30 }, Kbd: { props: { text: "⌘K" }, w: 60, h: 36 },
    Button: { props: { text: "Button", variant: "default" }, w: 140, h: 48 }, ButtonGroup: { props: { items: ["Prev", "Action", "Next"] }, w: 320, h: 48 }, Toggle: { props: { text: "Toggle" }, w: 100, h: 40 }, ToggleGroup: { props: { items: ["A", "B", "C"], mode: "multiple", activeItems: ["A"] }, w: 240, h: 40 },
    Input: { props: { placeholder: "Enter text...", label: "Label" }, w: 280, h: 68 }, Textarea: { props: { placeholder: "Write...", label: "Label" }, w: 280, h: 120 }, Checkbox: { props: { label: "Accept terms" }, w: 180, h: 36 }, Switch: { props: { label: "Dark mode" }, w: 160, h: 36 }, RadioGroup: { props: { options: ["Option 1", "Option 2"], value: "Option 1" }, w: 220, h: 100 }, Select: { props: { options: ["Option 1", "Option 2"], placeholder: "Select option", value: "Option 1" }, w: 280, h: 180 }, Combobox: { props: { options: ["Option 1", "Option 2"], placeholder: "Search options", value: "Option 1" }, w: 300, h: 280 }, DatePicker: { props: { placeholder: "Pick a date" }, w: 320, h: 380 }, Slider: { props: { value: 50 }, w: 240, h: 36 }, InputOTP: { props: { value: "12", length: 4 }, w: 220, h: 50 }, NativeSelect: { props: { options: ["Option 1", "Option 2"], value: "Option 1" }, w: 220, h: 44 }, Label: { props: { text: "Label" }, w: 120, h: 28 }, Form: { props: {}, w: 360, h: 200 },
    Card: { props: { title: "Card Title", description: "Description" }, w: 320, h: 120 }, Badge: { props: { text: "Badge", variant: "default" }, w: 100, h: 36 }, Avatar: { props: { fallback: "JD" }, w: 48, h: 48 }, Image: { props: { src: "https://placehold.co/800x400/1a1a2e/e0e0e0?text=Image", alt: "" }, w: 400, h: 220 }, Table: { props: { columns: ["Name", "Role", "Status"], rows: [["Alice", "Admin", "Active"], ["Bob", "User", "Pending"]] }, w: 420, h: 180 }, DataTable: { props: { columns: ["Name", "Role", "Status"], rows: [["Alice", "Admin", "Active"], ["Bob", "User", "Pending"]], searchKey: "Name" }, w: 460, h: 280 }, Calendar: { props: {}, w: 320, h: 360 }, Progress: { props: { value: 65 }, w: 240, h: 20 }, Skeleton: { props: {}, w: 240, h: 48 }, Spinner: { props: {}, w: 40, h: 40 }, Empty: { props: { title: "No data", description: "There is nothing to show yet." }, w: 300, h: 160 }, Carousel: { props: { items: ["Slide one", "Slide two", "Slide three"] }, w: 400, h: 240 },
    Tabs: { props: { tabs: [{ id: "t1", label: "Tab 1", content: "Content 1" }, { id: "t2", label: "Tab 2", content: "Content 2" }] }, w: 360, h: 180 }, Accordion: { props: { items: [{ id: "a1", title: "Section 1", content: "Content 1" }, { id: "a2", title: "Section 2", content: "Content 2" }] }, w: 360, h: 160 }, Breadcrumb: { props: { items: ["Home", "Products", "Current"] }, w: 320, h: 36 }, Pagination: { props: { pages: ["1", "2", "3"], activePage: "1" }, w: 320, h: 44 }, NavigationMenu: { props: { items: ["Home", "About", "Contact"] }, w: 440, h: 220 }, Menubar: { props: { items: ["File", "Edit", "View"] }, w: 360, h: 180 }, Sidebar: { props: { items: ["Dashboard", "Settings", "Users"] }, w: 240, h: 300 },
    Dialog: { props: { trigger: "Open Dialog", title: "Dialog Title", description: "Dialog description." }, w: 300, h: 100 }, AlertDialog: { props: { trigger: "Delete Item", title: "Are you sure?", description: "This cannot be undone." }, w: 300, h: 100 }, Sheet: { props: { trigger: "Open Sheet", title: "Sheet Panel", description: "Slide-over panel.", content: "Sheet body content." }, w: 200, h: 80 }, Drawer: { props: { trigger: "Open Drawer", title: "Drawer panel", description: "Bottom sheet content." }, w: 220, h: 80 }, Popover: { props: { trigger: "Open Popover", title: "Popover", content: "Popover content." }, w: 280, h: 180 }, HoverCard: { props: { trigger: "@synthex", title: "Synthex UI", description: "Cross-platform components." }, w: 280, h: 180 }, Tooltip: { props: { trigger: "Hover me", content: "Tooltip text" }, w: 220, h: 100 }, DropdownMenu: { props: { trigger: "Open Menu ▾", items: ["Edit", "Duplicate", "-", "Delete"] }, w: 240, h: 220 }, ContextMenu: { props: { trigger: "Right Click Area", items: ["Edit", "Delete"] }, w: 240, h: 220 }, Command: { props: { items: ["Open schematic", "Open console", "Export netlist"] }, w: 360, h: 260 }, Toast: { props: { title: "Toast!", description: "This is a toast notification." }, w: 300, h: 80 }, Alert: { props: { title: "Alert", description: "Something happened." }, w: 360, h: 80 }, Collapsible: { props: { trigger: "Toggle content", content: "This is the collapsible content." }, w: 320, h: 160 },
  };
  return map[type] || { props: {}, w: 200, h: 60 };
}
